### ISSUE TITLE
System.InvalidOperationException: StatSummary: Sequence contains no elements

### ISSUE THREAD

**Issue by ejsmith** [PerfDotNet/BenchmarkDotNet#104] opened 2016-02-26 20:22 UTC
I'm getting the following error. Any ideas what is wrong?

```
Unhandled Exception: System.InvalidOperationException: StatSummary: Sequence contains no elements
   at BenchmarkDotNet.Mathematics.Statistics..ctor(IEnumerable`1 values)
   at BenchmarkDotNet.Running.BenchmarkRunner.Execute(ILogger logger, Benchmark benchmark, IToolchain toolchain, BuildResult buildResult, IConfig config)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run(Benchmark benchmark, ILogger logger, IConfig config)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run(IList`1 benchmarks, ILogger logger, String title, IConfig config)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run(IList`1 benchmarks, IConfig config)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run[T](IConfig config)
   at Benchmarks.Program.Main(String[] args) in C:\Projects\Foundatio\src\Benchmarks\Program.cs:line 10
```

**Comment by adamsitnik** [comment] 2016-02-26 20:33
Most probably one of the methods marked as [Benchmark] fails, exception gets swallowed and there is no data to calculate for stats

**Comment by adamsitnik** [comment] 2016-02-26 20:33
Most probably one of the methods marked as [Benchmark] fails, exception gets swallowed and there is no data to calculate for stats

**Comment by mattwarren** [comment] 2016-03-01 17:34
This has now come up twice, so I think we need to do something better here. 

- [ ] Make the original exception more obvious
- [ ] Stop the 2nd LINQ exception from happening, as it's not the root cause and it's confusing.

I'll take a look

**Comment by adamsitnik** [comment] 2016-03-01 21:10
Currently exception occurs in separate process, we just read the output from it, check the exit code and later on try to parse the results. So it looks like there is exception, but it is only a redirected output.

Maybe we should do some kind of a initial verification first? Like calling SetUp once and then each Benchmark before doing the initial job?

**Comment by mattwarren** [comment] 2016-03-03 19:22
With the changes I just pushed you get the output as shown below. I think this is enough for this issue.

Note the error in red (displayed when the benchmark throws an error) and the extra summary error at the end showing a list of which benchmarks had errors. 

Note: the summary error should have always been there, it's just that the LINQ error (StatSummary: Sequence contains no elements) was hiding/masking it.

![benchmark output when an exception is thrown](https://cloud.githubusercontent.com/assets/157298/13506171/b74938de-e174-11e5-8a1b-2d623a5e622e.png)

**Closed** 2016-03-05 00:55 UTC
Labels: bug
