### ISSUE TITLE
CompositeValidator: some validators will be skipped

### ISSUE THREAD

**Issue by ig-sinicyn** [PerfDotNet/BenchmarkDotNet#181] opened 2016-05-16 07:15 UTC
CompositeValidator.cs
**1**

 ```cs
        public CompositeValidator(IValidator[] configuredValidators)
        {
            Validators = configuredValidators
                .Concat(MandatoryValidators)
                .GroupBy(valiadator => valiadator.GetType())
                .Select(grouppedByType => grouppedByType.FirstOrDefault(validator => validator.TreatsWarningsAsErrors) ?? grouppedByType.First())
                .Distinct()
                .ToArray();
        }
```
 * typos: valiadator, grouppedByType 
 * if user adds multiple instances of the validator with different options, only one will be run. It will be better to throw exception with "Fix the validators bla-bla-bla" message instead:)

**2**
```cs
        public bool TreatsWarningsAsErrors => Validators.All(validator => validator.TreatsWarningsAsErrors);
```
* bad news: validator with TreatsWarningsAsErrors = false will win.
* good news: the property is not used at all :)

**Comment by AndreyAkinshin** [comment] 2016-05-16 07:20
Thanks for the report. Will be fixed in the next version.

**Comment by adamsitnik** [comment] 2016-05-17 22:26
> if user adds multiple instances of the validator with different options, only one will be run. It will be better to throw exception with "Fix the validators bla-bla-bla" message instead:)

The stronger validator (TreatsWarningsAsErrors  = true) will always win and only one will be used. There is no need to throw (it can be an effect of merging two valid configs). To me this is a desired behaviour, I have even [written test for that](https://github.com/PerfDotNet/BenchmarkDotNet/blob/master/BenchmarkDotNet.Tests/CompositeValidatorTests.cs#L10). "Is's not a bug, it's a feature" ;)

> good news: the property is not used at all :)

It's used in unit tests, however it is not a good practice ;)

cc @ig-sinicyn @AndreyAkinshin

**Comment by adamsitnik** [comment] 2016-05-26 02:05
I have made it internall and fixed the typos.

**Closed** 2016-05-29 20:48 UTC
Labels: fixed-in-develop
