### ISSUE TITLE
[NeedHelp] Benchmarks takes too long to run.

### ISSUE THREAD

**Issue by ig-sinicyn** [PerfDotNet/BenchmarkDotNet#126] opened 2016-03-22 12:26 UTC
Hi!

I'm trying to enable BenchmarkDotNet to be used as perf tests runner and I stuck with a performance problem (no pun intended:)). 

The benchmark with a ~20 candidate methods takes five minutes or so to complete. If I didn't do something wrong, all costs is on the runner side. Benchmark code being run in-process finishes in a second.
[Proof (summary output + code (scroll down))](https://gist.github.com/ig-sinicyn/4ea179c4549462cbe493).

The timings are ok for benchmarks as they never meant to run on a regular basis.
But five minutes is a bit too long for perf tests, especially when there are hundreds of them;)

So:
0. Can I do anything to speedup the tests right now?
1. Any plans to reduce bootstrapping overhead?
2. Will it be possible to run benchmarks in-process, even at cost of slightly inaccurate results?

Thanks!

**Comment by adamsitnik** [comment] 2016-03-22 13:15
Right now you can only try with the configuration (reduce Launch/Wamup/Target count, don't use all default Exporters, more?).

Recently I have worked on [slow export](https://github.com/PerfDotNet/BenchmarkDotNet/pull/124). I would be very happy to tune the rest. 

How I am planning to contribute to BDN:
* fix all known bugs
* tune perf
* introduce parallel benchmark runner
* create extension for regression tests

**Comment by ig-sinicyn** [comment] 2016-03-22 13:30
Ok, thanks!

The execution time is 66.81 sec with the following config
```
        public FastRunConfig()
        {
            Add(new Job
            {
                IterationTime = 100,
                LaunchCount = 1,
                WarmupCount = 1,
                TargetCount = 2
            });
        }
```
and the results are still pretty accurate. Much better:)

**Comment by mattwarren** [comment] 2016-03-22 13:43
Can you post the full log, I'd like to get rough idea of where the 5 mins is spent (i.e. bootstrapping, execution, results, runner, etc).

> Benchmark code being run in-process finishes in a second.

Yes, but BenchmarkDotNet runs each benchmark 100's or even 1000's of times and it will also launch multiple processes and run benchmarks in those. For example here's one "Launch" of a benchmark (by default 3 "launches" are done), where `4096 op` means we called the `[Benchmark]` methods 4096 times.

```
Pilot 1: 4 op, 27473419.29 ns, 6.8684 ms/op
Pilot 2: 8 op, 28321082.76 ns, 3.5401 ms/op
Pilot 3: 16 op, 28529767.62 ns, 1.7831 ms/op
Pilot 4: 32 op, 28939534.99 ns, 904.3605 us/op
Pilot 5: 64 op, 30052140.81 ns, 469.5647 us/op
Pilot 6: 128 op, 34293499.11 ns, 267.9180 us/op
Pilot 7: 256 op, 40987379.7 ns, 160.1070 us/op
Pilot 8: 512 op, 55791461.1 ns, 108.9677 us/op
Pilot 9: 1024 op, 86148836.78 ns, 84.1297 us/op
Pilot 10: 2048 op, 143543636.23 ns, 70.0897 us/op
Pilot 11: 4096 op, 254962347.4 ns, 62.2467 us/op

IdleWarmup 1: 4096 op, 45234.06 ns, 11.0435 ns/op
IdleWarmup 2: 4096 op, 9122.84 ns, 2.2273 ns/op
IdleWarmup 3: 4096 op, 9122.84 ns, 2.2273 ns/op
IdleWarmup 4: 4096 op, 8742.72 ns, 2.1345 ns/op
IdleWarmup 5: 4096 op, 18245.67 ns, 4.4545 ns/op
IdleWarmup 6: 4096 op, 9122.84 ns, 2.2273 ns/op
IdleWarmup 7: 4096 op, 30409.45 ns, 7.4242 ns/op

IdleTarget 1: 4096 op, 26608.27 ns, 6.4962 ns/op
IdleTarget 2: 4096 op, 7222.24 ns, 1.7632 ns/op
IdleTarget 3: 4096 op, 6842.13 ns, 1.6704 ns/op
IdleTarget 4: 4096 op, 8742.72 ns, 2.1345 ns/op
IdleTarget 5: 4096 op, 63099.61 ns, 15.4052 ns/op
IdleTarget 6: 4096 op, 31169.69 ns, 7.6098 ns/op
IdleTarget 7: 4096 op, 27368.51 ns, 6.6818 ns/op
IdleTarget 8: 4096 op, 8362.6 ns, 2.0417 ns/op
IdleTarget 9: 4096 op, 53216.54 ns, 12.9923 ns/op
IdleTarget 10: 4096 op, 28888.98 ns, 7.0530 ns/op
IdleTarget 11: 4096 op, 29269.1 ns, 7.1458 ns/op
IdleTarget 12: 4096 op, 33830.52 ns, 8.2594 ns/op
IdleTarget 13: 4096 op, 33830.52 ns, 8.2594 ns/op
IdleTarget 14: 4096 op, 31549.81 ns, 7.7026 ns/op
IdleTarget 15: 4096 op, 26608.27 ns, 6.4962 ns/op
IdleTarget 16: 4096 op, 26988.39 ns, 6.5890 ns/op
IdleTarget 17: 4096 op, 26228.15 ns, 6.4034 ns/op
IdleTarget 18: 4096 op, 26988.39 ns, 6.5890 ns/op

MainWarmup 1: 4096 op, 256667557.41 ns, 62.6630 us/op
MainWarmup 2: 4096 op, 254377725.68 ns, 62.1039 us/op
MainWarmup 3: 4096 op, 254070210.1 ns, 62.0289 us/op
MainWarmup 4: 4096 op, 253919683.32 ns, 61.9921 us/op
MainWarmup 5: 4096 op, 255050534.81 ns, 62.2682 us/op
MainWarmup 6: 4096 op, 255150886 ns, 62.2927 us/op
MainWarmup 7: 4096 op, 257366214.57 ns, 62.8335 us/op

MainTarget 1: 4096 op, 258645692.25 ns, 63.1459 us/op
MainTarget 2: 4096 op, 259275548.03 ns, 63.2997 us/op
MainTarget 3: 4096 op, 257828818.35 ns, 62.9465 us/op
MainTarget 4: 4096 op, 255755653.97 ns, 62.4403 us/op
MainTarget 5: 4096 op, 257432735.24 ns, 62.8498 us/op
MainTarget 6: 4096 op, 258752885.57 ns, 63.1721 us/op
MainTarget 7: 4096 op, 254291438.87 ns, 62.0829 us/op
MainTarget 8: 4096 op, 256610919.81 ns, 62.6492 us/op
MainTarget 9: 4096 op, 256853435.18 ns, 62.7084 us/op
MainTarget 10: 4096 op, 256399194 ns, 62.5975 us/op

Result 1: 4096 op, 258618513.81 ns, 63.1393 us/op
Result 2: 4096 op, 259248369.58 ns, 63.2931 us/op
Result 3: 4096 op, 257801639.91 ns, 62.9399 us/op
Result 4: 4096 op, 255728475.52 ns, 62.4337 us/op
Result 5: 4096 op, 257405556.8 ns, 62.8432 us/op
Result 6: 4096 op, 258725707.12 ns, 63.1655 us/op
Result 7: 4096 op, 254264260.42 ns, 62.0762 us/op
Result 8: 4096 op, 256583741.36 ns, 62.6425 us/op
Result 9: 4096 op, 256826256.74 ns, 62.7017 us/op
Result 10: 4096 op, 256372015.55 ns, 62.5908 us/op
```

**Comment by mattwarren** [comment] 2016-03-22 13:48
> Will it be possible to run benchmarks in-process, even at cost of slightly inaccurate results?

There's a specific reason for running out-of-process, see ["Use separate CLR instances"](https://github.com/PerfDotNet/PerformanceBook.NET/blob/master/science/microbenchmarking.adoc#use-separate-clr-instances) in @AndreyAkinshin WIP book for more info.

> The execution time is 66.81 sec with the following config
> ```
        public FastRunConfig()
        {
            Add(new Job
            {
                IterationTime = 100,
                LaunchCount = 1,
                WarmupCount = 1,
                TargetCount = 2
            });
        }
```

Yeah you can always shorten the default values, that's fine it they work for you. 

But BenchmarkDotNet has higher default values to ensure it's always accurate. It maybe that the default values are conservative and slow, but that's better than being inaccurate.

**Comment by ig-sinicyn** [comment] 2016-03-22 14:26
@mattwarren
>Can you post the full log, I'd like to get rough idea of where the 5 mins is spent 

Ok, I attached all content of the `release` folder in case you needed it.
[Release.zip](https://github.com/PerfDotNet/BenchmarkDotNet/files/184250/Release.zip)


>There's a specific reason for running out-of-process
> ... but that's better than being inaccurate

Completely agreed. However, there are use cases when having slightly varying results is expected and even appreciated. To name one, trying to estimate the performance of the code in a real-world conditions.

In fact, this is what I'm trying to do - to use BenchDotNet as a base for competition performance tests. These are special beast as they are not trying to proofcheck _absolute_ performance metrics.

Instead of this the goal is to put a set of implementations + baseline one in the same conditions and to proof that all of them will not break some limits. The important part is, these limits are relative and based on baseline' values.
In fact, you do not want to run competition under cleanroom conditions as the code may perform much worse in production. So, some side effects from JIT / assembly loading / IO activity / network latency etc are good ones as they help to proof that our estimates are not too optimistic:)

**NB:** It's important to always run the competition in random order for more (or less:)) uniform distribution, but it does not look like a big deal.

**Comment by AndreyAkinshin** [comment] 2016-03-23 09:09
Hi @ig-sinicyn, thank you for the question. I added some brief info to README: https://github.com/PerfDotNet/BenchmarkDotNet/tree/develop#faq

> In fact, you do not want to run competition under cleanroom conditions as the code may perform much worse in production.

You can't create a good benchmark based on code without a steady state. You should create a cleanroom conditions that emulates production environment.

>  JIT / assembly loading

We can use `Mode.SingleRun` (see https://github.com/PerfDotNet/BenchmarkDotNet/tree/develop#jobs) for measuring first run of the method. However, in general case, if you want to compare performance of two methods, you usually want to do it without side-effects.

> network latency

It is a very good point. For now, BenchmarkDotNet is designed for microbenchmarks without network interactions. If you have any network operations, it would be a good decision to specify amount of iteration manually.

>  It's important to always run the competition in random order for more (or less:)) uniform distribution

Interesting point. But when does it matter? We already have a separated process per benchmark and launch it several times. I think, if you have different results for different benchmark method orders, then your benchmark is a bad one. In this case, you should investigate cause of such behavior instead of using of average randomized results.

**Comment by ig-sinicyn** [comment] 2016-03-23 10:43
@AndreyAkinshin 

>You can't create a good benchmark based on code without a steady state

If you want to use benchmark to measure something - yes, agreed:).
If you want to use benchmark to proof some worst-case limits - it's not completely true. 

For the last case, all you need is to run a set of candidates together with a baseline benchmark and to compare result values as a relative to the baseline. 
Slightly unstable conditions is good there as they helps to check  that our relative limits are not too tight:)

>Interesting point. But when does it matter? 

It does matter only if you want to add some random latency into benchmark but you do not want some tests systematically suffer from side effects more than others. Let's say, running all tests in-process, waiting for IO or something else like this,


> I think, if you have different results for different benchmark method orders, then your benchmark is a bad one.

Agreed again;) This is true for time-measuring benchmarks,
For realworld-scenario-based perftests, having different results for different runs is quite common. You just take estimates not on average timings but on Nth percentile of the results.
Some more info on this:
http://www.goland.org/average_percentile_services/
http://apmblog.dynatrace.com/2012/11/14/why-averages-suck-and-percentiles-are-great/

**Comment by AndreyAkinshin** [comment] 2016-03-23 10:53
@ig-sinicyn, thanks for the links. I will try to create some easy API for such scenarios.

**Comment by ig-sinicyn** [comment] 2016-03-23 11:21
@AndreyAkinshin 
I've done some already and I'm going to do PR as it will be ready to use.

If you want to check what will it look like, here's the code: 
https://github.com/rsdn/CodeJam/tree/master/Main/tests-performance
All the code from BenchmarkDotNet namespace will go into PR.
And some test examples (not a finite set yet) are here:
https://github.com/rsdn/CodeJam/tree/master/Main/tests-performance/CalibrationBenchmarks

Note that namespaces and the structure of the code is not final. Almost all code does not need to reference NUnit, for example. I'll do final refactoring after I'll cover most of our use cases,
Discussion on a final design [will be here](http://rsdn.ru/forum/prj.codejam/6389792) (in Russian, sorry)

**Comment by AndreyAkinshin** [comment] 2016-03-23 12:55
Looks good, waiting for the PR.

Continuous testing and good NUnit/XUnit support is an important task, we definitely going to do it. However, we should do it carefully, because it is very easy to write bad useless benchmarks, so, I want to write some baseline based API for asserts. Hopefully, it will help to write good benchmark tests.

> Discussion on a final design

Looks interesting.

**Comment by ig-sinicyn** [comment] 2016-03-23 13:33
> However, we should do it carefully, because it is very easy to write bad useless benchmarks, so, I want to write some baseline based API for asserts. Hopefully, it will help to write good benchmark tests.

Agreed completely. 

Also, I'm going to split changes into multiple pull requests.
This way you can pull some small and (used to be) usable changes (such as adding Percentile() method into Statistics class and adding Percentile/ScaledPercentile columns) and reject others if they don't fit well.

Is it ok?

**Comment by AndreyAkinshin** [comment] 2016-03-23 13:40
Sounds good to me.

**Comment by mattwarren** [comment] 2016-05-19 08:37
Closing this, I think the question has been answered.

**Closed by mattwarren** 2016-05-19 08:37 UTC
Labels: question
